from .base import ToolSpec
from . import (
    alphafold,
    bgee,
    bindingdb,
    cellxgene,
    chebi,
    chembl,
    clinvar,
    clinvar_variation,
    clinicaltrials,
    civic,
    efo,
    ensembl,
    gnomad,
    gwas_catalog,
    human_protein_atlas,
    mutation,
    ncbi_blast,
    ncbi_gene,
    opentargets,
    pharmgkb,
    pride,
    pubmed,
    pubchem,
    quickgo,
    reactome,
    rcsb_pdb,
    sequence,
    stringdb,
    uniprot,
)

REGISTRY: dict[str, ToolSpec] = {
    sequence.ANALYZE_SPEC.name: sequence.ANALYZE_SPEC,
    sequence.ALIGN_PAIRWISE_SPEC.name: sequence.ALIGN_PAIRWISE_SPEC,
    uniprot.SEARCH_SPEC.name: uniprot.SEARCH_SPEC,
    uniprot.FETCH_SPEC.name: uniprot.FETCH_SPEC,
    pubmed.SEARCH_SPEC.name: pubmed.SEARCH_SPEC,
    pubmed.FETCH_METADATA_SPEC.name: pubmed.FETCH_METADATA_SPEC,
    pubmed.FETCH_ABSTRACT_SPEC.name: pubmed.FETCH_ABSTRACT_SPEC,
    mutation.DIFF_SPEC.name: mutation.DIFF_SPEC,
    alphafold.FETCH_PREDICTION_SPEC.name: alphafold.FETCH_PREDICTION_SPEC,
    bgee.LOOKUP_EXPRESSION_SPEC.name: bgee.LOOKUP_EXPRESSION_SPEC,
    bindingdb.LOOKUP_LIGANDS_SPEC.name: bindingdb.LOOKUP_LIGANDS_SPEC,
    cellxgene.FETCH_COLLECTION_SPEC.name: cellxgene.FETCH_COLLECTION_SPEC,
    chebi.SEARCH_COMPOUNDS_SPEC.name: chebi.SEARCH_COMPOUNDS_SPEC,
    chebi.FETCH_COMPOUND_SPEC.name: chebi.FETCH_COMPOUND_SPEC,
    clinvar.SEARCH_SPEC.name: clinvar.SEARCH_SPEC,
    reactome.SEARCH_PATHWAYS_SPEC.name: reactome.SEARCH_PATHWAYS_SPEC,
    reactome.FETCH_PATHWAY_SPEC.name: reactome.FETCH_PATHWAY_SPEC,
    quickgo.SEARCH_TERMS_SPEC.name: quickgo.SEARCH_TERMS_SPEC,
    quickgo.FETCH_TERM_SPEC.name: quickgo.FETCH_TERM_SPEC,
    efo.SEARCH_TERMS_SPEC.name: efo.SEARCH_TERMS_SPEC,
    efo.FETCH_TERM_SPEC.name: efo.FETCH_TERM_SPEC,
    ensembl.LOOKUP_GENE_SPEC.name: ensembl.LOOKUP_GENE_SPEC,
    ensembl.FETCH_XREFS_SPEC.name: ensembl.FETCH_XREFS_SPEC,
    ncbi_gene.SEARCH_GENE_SPEC.name: ncbi_gene.SEARCH_GENE_SPEC,
    ncbi_gene.FETCH_GENE_SPEC.name: ncbi_gene.FETCH_GENE_SPEC,
    clinicaltrials.SEARCH_STUDIES_SPEC.name: clinicaltrials.SEARCH_STUDIES_SPEC,
    stringdb.INTERACTION_PARTNERS_SPEC.name: stringdb.INTERACTION_PARTNERS_SPEC,
    stringdb.NETWORK_SPEC.name: stringdb.NETWORK_SPEC,
    chembl.SEARCH_MOLECULES_SPEC.name: chembl.SEARCH_MOLECULES_SPEC,
    chembl.SEARCH_TARGETS_SPEC.name: chembl.SEARCH_TARGETS_SPEC,
    clinvar_variation.SEARCH_CLINICAL_TABLES_SPEC.name: clinvar_variation.SEARCH_CLINICAL_TABLES_SPEC,
    clinvar_variation.FETCH_REFSNP_SPEC.name: clinvar_variation.FETCH_REFSNP_SPEC,
    gnomad.FETCH_VARIANT_SPEC.name: gnomad.FETCH_VARIANT_SPEC,
    gwas_catalog.SEARCH_STUDIES_SPEC.name: gwas_catalog.SEARCH_STUDIES_SPEC,
    gwas_catalog.SEARCH_ASSOCIATIONS_SPEC.name: gwas_catalog.SEARCH_ASSOCIATIONS_SPEC,
    opentargets.SEARCH_SPEC.name: opentargets.SEARCH_SPEC,
    opentargets.FETCH_TARGET_DISEASES_SPEC.name: opentargets.FETCH_TARGET_DISEASES_SPEC,
    civic.TYPEAHEAD_SPEC.name: civic.TYPEAHEAD_SPEC,
    civic.VARIANT_EVIDENCE_SPEC.name: civic.VARIANT_EVIDENCE_SPEC,
    human_protein_atlas.FETCH_GENE_SPEC.name: human_protein_atlas.FETCH_GENE_SPEC,
    rcsb_pdb.SEARCH_ENTRIES_SPEC.name: rcsb_pdb.SEARCH_ENTRIES_SPEC,
    rcsb_pdb.FETCH_ENTRY_SPEC.name: rcsb_pdb.FETCH_ENTRY_SPEC,
    pharmgkb.SEARCH_CLINICAL_ANNOTATIONS_SPEC.name: pharmgkb.SEARCH_CLINICAL_ANNOTATIONS_SPEC,
    pharmgkb.FETCH_CLINICAL_ANNOTATION_SPEC.name: pharmgkb.FETCH_CLINICAL_ANNOTATION_SPEC,
    ncbi_blast.RUN_SEARCH_SPEC.name: ncbi_blast.RUN_SEARCH_SPEC,
    pride.SEARCH_PROJECTS_SPEC.name: pride.SEARCH_PROJECTS_SPEC,
    pride.FETCH_PROJECT_SPEC.name: pride.FETCH_PROJECT_SPEC,
    pubchem.LOOKUP_COMPOUND_SPEC.name: pubchem.LOOKUP_COMPOUND_SPEC,
}

__all__ = ["ToolSpec", "REGISTRY"]
